# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cybcp7spj-capi-aws
  namespace: cybcp7spj
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cybcp7spj-capi-aws
subjects:
- kind: ServiceAccount
  name: cybcp7spj-capi-aws
